development:
  adapter: postgres
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  database: ${DB_NAME:freshgo}
  username: ${DB_USER:postgres}
  password: ${DB_PASSWORD:}
  sslmode: ${DB_SSLMODE:disable}
  max_open_conns: ${DB_MAX_OPEN_CONNS:25}
  max_idle_conns: ${DB_MAX_IDLE_CONNS:5}
  conn_max_lifetime: ${DB_CONN_MAX_LIFETIME:300s}

test:
  adapter: postgres
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  database: ${DB_NAME:freshgo_test}
  username: ${DB_USER:postgres}
  password: ${DB_PASSWORD:}
  sslmode: ${DB_SSLMODE:disable}
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: 60s

production:
  adapter: postgres
  host: ${DB_HOST}
  port: ${DB_PORT:5432}
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  sslmode: ${DB_SSLMODE:require}
  max_open_conns: ${DB_MAX_OPEN_CONNS:100}
  max_idle_conns: ${DB_MAX_IDLE_CONNS:25}
  conn_max_lifetime: ${DB_CONN_MAX_LIFETIME:600s}
